admin_module/urls.py
from django.urls import path
from . import views_city, views_currency, views_admin, views, views_gpa_code, views_subclass, views_commission, \
    views_exchange, views_kzd_rates, views_oi_rates, views_sdr_rates

app_name = 'admin_module'
urlpatterns = [
    path('', views.home, name='home'),
    path('main/', views.main, name='main'),
    path('login/', views.login_view, name='login'),
    path('dictionaries/', views.dictionaries_view, name='dictionaries'),
    
    path('records/',views.records, name="records"),
    path('reports/',views.reports, name="reports"),
    path('reports/cn51',views.report_cn51, name="report_cn51"),
    path('calculate_cost/', views.calculate_cost, name='calculate_cost'),

    path('add_user/', views_admin.add_user, name='add_user'),
    path('edit_user/<int:user_id>/', views_admin.edit_user, name='edit_user'),
    path('block_user/<int:user_id>/', views_admin.block_user, name='block_user'),
    path('user_list/', views_admin.user_list, name='user_list'),


    path('cities/', views_city.cities, name='cities'),
    path('cities/edit/<int:city_id>/', views_city.edit_city, name='edit_city'),
    path('cities/delete/<int:city_id>/', views_city.delete_city, name='delete_city'),
    path('upload_excel_cities', views_city.upload_excel_cities, name="upload_excel_cities"),
    
    path('currencies/', views_currency.currencies, name="currencies"),
    path('currencies/edit/<int:currency_id>/', views_currency.edit_currency, name='edit_currency'),
    path('currencies/delete/<int:currency_id>/', views_currency.delete_currency, name='delete_currency'),


    path('exchange_rates/', views_exchange.exchange_rates, name='exchange_rates'),
    path('delete_exchange_rate/<int:exchange_rate_id>/', views_exchange.delete_exchange_rate, name="delete_exchange_rate"),


    path('gpa_code/', views_gpa_code.gpa_code, name="gpa_code"),
    path('gpa_code/edit/<int:gpa_code_id>/', views_gpa_code.edit_gpa_code, name='edit_gpa_code'),
    path('gpa_code/delete/<int:gpa_code_id>/', views_gpa_code.delete_gpa_code, name='delete_gpa_code'),

    path('subclass/', views_subclass.subclass, name="subclass"),
    path('edit_subclass/<int:subclass_id>/', views_subclass.edit_subclass, name="edit_subclass"),
    path('delete_subclass/<int:subclass_id>/', views_subclass.delete_subclass, name="delete_subclass"),

    path('commission', views_commission.commission, name='commission'),
    path('commission/edit/<int:commission_id>/', views_commission.edit_commission, name='edit_commission'),
    path('commission/delete/<int:commission_id>/', views_commission.delete_commission, name='delete_commission'),

    path('kzd_rates', views_kzd_rates.kzd_rates, name="kzd_rates"),
    path('edit_kzd_rate/<int:kzd_rate_id>/', views_kzd_rates.edit_kzd_rate, name="edit_kzd_rate"),
    path('delete_kzd_rate/<int:kzd_rate_id>/', views_kzd_rates.delete_kzd_rate, name="delete_kzd_rate"),
    path('upload_excel', views_kzd_rates.upload_excel, name="upload_excel"),
    
    path('oi_rates', views_oi_rates.oi_rates, name="oi_rates"),
    path('oi_rates/edit/<int:oi_rates_id>/', views_oi_rates.edit_oi_rates, name='edit_oi_rates'),
    path('oi_rates/delete/<int:oi_rates_id>/', views_oi_rates.delete_oi_rates, name='delete_oi_rates'),

    path('sdr_rates/', views_sdr_rates.sdr_rates, name='sdr_rates'),
    path('sdr_rates/edit/<int:sdr_rates_id>/', views_sdr_rates.edit_sdr_rates, name='edit_sdr_rates'),
    path('sdr_rates/delete/<int:sdr_rates_id>/', views_sdr_rates.delete_sdr_rates, name='delete_sdr_rates'),
    path('upload_excel_sdr', views_sdr_rates.upload_excel_sdr, name="upload_excel_sdr"),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),  # Ссылка на административную панель Django
    path('', include('admin_module.urls')),  # Ссылка на ваш административный модуль

]

admin_module/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from .models import UserProfile, City, Currency, ExchangeRate, GPACode, Subclass, Commission, KZDRate, OIRate, SdrRate


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'}))


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('roles', 'status')


class CurrencyForm(forms.ModelForm):
    class Meta:
        model = Currency
        fields = '__all__'


class AddExchangeRateForm(forms.ModelForm):
    value = forms.DecimalField(max_digits=10, decimal_places=5, label='Значение')
    rate_1 = forms.ModelChoiceField(queryset=Currency.objects.all(), label='Валюта 1')
    rate_2 = forms.ModelChoiceField(queryset=Currency.objects.all(), label='Валюта 2')

    class Meta:
        model = ExchangeRate
        fields = ('value', 'rate_1', 'rate_2', 'value')


class UploadExcelForm(forms.Form):
    excel_file = forms.FileField()


class GPACodeForm(forms.ModelForm):
    class Meta:
        model = GPACode
        fields = ['gpa_code', 'description', 'gpa_full_name', 'oracle_code', 'currency']


class SubclassForm(forms.ModelForm):
    class Meta:
        model = Subclass
        fields = ['name_code', 'name_description']



class CommissionForm(forms.ModelForm):
    gpa = forms.ModelChoiceField(queryset=GPACode.objects.all())  
    class Meta:
        model = Commission
        fields = ['gpa', 'value']


class KZDRateForm(forms.ModelForm):
    city_1 = forms.ModelChoiceField(queryset=City.objects.all())
    city_2 = forms.ModelChoiceField(queryset=City.objects.all())

    class Meta:
        model = KZDRate
        fields = '__all__'
        widgets = {
            'date_begin': forms.DateInput(attrs={'type': 'date'}),
            'date_end': forms.DateInput(attrs={'type': 'date'}),
        }


class OIRateForm(forms.ModelForm):
    city_1 = forms.ModelChoiceField(queryset=City.objects.all(), empty_label="Select City 1"),
    city_2 = forms.ModelChoiceField(queryset=City.objects.all(), empty_label="Select City 2")
    class Meta:
        model = OIRate
        fields = ['city_1', 'city_2', 'gpa_id', 'rate','date_begin', 'date_end']
        widgets = {
            'date_begin': forms.DateInput(attrs={'type': 'date'}),
            'date_end': forms.DateInput(attrs={'type': 'date'}),
        }



class SdrRateForm(forms.ModelForm):
    city_1 = forms.ModelChoiceField(queryset=City.objects.all(), empty_label="Select City 1"),
    city_2 = forms.ModelChoiceField(queryset=City.objects.all(), empty_label="Select City 2")

    class Meta:
        model = SdrRate
        fields = '__all__'
        widgets = {
            'date_begin': forms.DateInput(attrs={'type': 'date'}),
            'date_end': forms.DateInput(attrs={'type': 'date'}), }


class ExcelUploadForm(forms.Form):
    excel_file = forms.FileField(label='Select an Excel file')



class ExcelImportForm(forms.Form):
    excel_file = forms.FileField()
    def clean_excel_file(self):
        excel_file = self.cleaned_data.get('excel_file')
        if excel_file:
            # Проверяем, является ли файл допустимым типом (например, .xls или .xlsx)
            allowed_extensions = ['.xls', '.xlsx']
            if not any(extension in excel_file.name for extension in allowed_extensions):
                raise forms.ValidationError('Пожалуйста, загрузите файл с расширением .xls или .xlsx.')

        return excel_file

admin_module/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from .forms import LoginForm,ExcelImportForm
import pandas as pd
from django.utils import timezone
from .models import *
from datetime import datetime
from reportlab.pdfgen import canvas
from django.db.models import Sum
from django.http import HttpResponse
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle,Spacer,Paragraph
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle


def records(request):
    if request.method == 'POST':
        form = ExcelImportForm(request.POST, request.FILES)
        if form.is_valid():
            excel_file = request.FILES['excel_file']
            df = pd.read_excel(excel_file)

            # Process DataFrame and save to the database
            for index, row in df.iterrows():
                Records.objects.create(
                    GPACode=row['GPACode'],
                    Origin=row['Origin'],
                    Destination=row['Destination'],
                    Subclass=row['Subclass'],
                    Flight1=row['Flight1'],
                    FltDate=row['FltDate'],
                    Wgt=row['Wgt'],
                    Depeche=row['Depeche'],
                    GroupDate=row['Group Date'],
                    created_by=request.user.username,
                    modified_by=request.user.username,
                    created_date = timezone.now(),
                    modified_date = timezone.now()
                )

            # Redirect to the records page
            return redirect('admin_module:records')

    else:
        form = ExcelImportForm()

    # Retrieve all records from the Report model
    records = Records.objects.all()

    # Pass the records and form to the template
    return render(request, 'admin_module/records.html', {'records': records, 'form': form})

def calculate_cost(request):
    # Получаем все записи, где Origin = 'ALA' и Destination = 'FRU'
    records = Records.objects.filter(Origin='ALA', Destination='FRU')

    # Получаем тариф для ALA -> FRU
    tariff = SdrRate.objects.filter(city_1__city_code='ALA', city_2__city_code='FRU').first()

    if tariff is not None:
        # Рассчитываем общую стоимость
        total_cost = records.aggregate(Sum('Wgt'))['Wgt__sum'] * tariff.rate
    else:
        total_cost = None

    # Получаем данные из записи Records
    records_data = Records.objects.filter(Origin='ALA', Destination='FRU').first()

    # Получаем данные из записи SdrRate
    sdr_rate_data = SdrRate.objects.filter(city_1__city_code='ALA', city_2__city_code='FRU').first()

    # Создаем PDF-документ с результатами
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="cost_calculation.pdf"'

    # Устанавливаем размер страницы
    pdf = SimpleDocTemplate(response, pagesize=letter)

    # Определяем столбцы и строки для таблицы
    columns = ["Parcours pats de destination ou groupes",
               "Categones d'envos",
               "Poids transpote au cors du ou des mois",
               "Poids total",
               "Prix du transport par kg",
               "Total des frais de transport a paye"]

    data = [
        ["1", "2", "3", "4", "5", "6"],
        ["", "Prioritaire", "kg", "kg", "SDR", "SDR"],
        ["ALA_FRU", "CP",
         str(records_data.Wgt) if records_data else "N/A",
         str(records_data.Wgt) if records_data else "N/A",
         str(sdr_rate_data.rate) if sdr_rate_data else "N/A",
         f"{total_cost:.2f}" if total_cost is not None else "N/A"],
        ["Total general", "", ""]
    ]

    # Формируем таблицу
    table_data = [columns] + data
    table = Table(table_data, colWidths=[100] * len(columns))

    # Настраиваем стиль таблицы
    style = TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)])

    table.setStyle(style)

    # Получаем стиль 'Heading2'
    heading2_style = getSampleStyleSheet()['Heading2']

    # Собираем документ
    elements = [
    table, Spacer(1, 12), Spacer(1, 12),
    Spacer(1, 6),
    Paragraph(
        "<u>Administration creancire</u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<u>Vue et accepte par l'Administration debitrice</u>",
        style=ParagraphStyle(
            'Heading2',
            fontSize=10,
            spaceBefore=100,
            spaceAfter=6,
        )
    ),

    Paragraph(
            "<u>Signature</u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<u>Lieu,date et signature</u>",

              style=ParagraphStyle(
                  'Heading2',
                  fontSize=10,
                  spaceBefore=6,
                  spaceAfter=6,
              )
              )
]

    pdf.build(elements)


    return response


def home(request):
    return render(request, 'admin_module/admin_home.html')


def main(request):
    return render(request, 'admin_module/main.html')   

def reports(request):
    return render(request, 'admin_module/reports.html')   

def report_cn51(request):
    return render(request, 'admin_module/report_cn51.html')   


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('admin_module:main')
    else:
        form = LoginForm()

    return render(request, 'admin_module/login.html', {'form': form})


def dictionaries_view(request):
    return render(request, 'admin_module/dictionaries.html')

admin_module/templates/dictionaries/cities.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Cities</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </head>
    <script>
        $(document).ready(function() {
            console.log("Document ready.");
    
            function performSearch() {
                var searchQuery = $("#search-city").val().trim().toLowerCase();
    
                $(".city-code").each(function() {
                    var cityCode = $(this).text().trim().toLowerCase();
                    var row = $(this).closest("tr");
    
                    if (cityCode.includes(searchQuery)) {
                        row.show();
                    } else {
                        row.hide();
                    }
                });
            }
    
            $("#add-city-button").click(function() {
                console.log("Add button clicked.");
                $("#add-city-form").toggle();
            });
    
            $("#search-button").click(function() {
                performSearch();
            });
    
            $("#search-city").on("input", function() {
                performSearch();
            });
        });
    </script>
     <script>
        $(document).ready(function() {
            console.log("Страница загружена.");

            $("#add-rate-button").click(function() {
                console.log("Кнопка 'Добавить' нажата.");
                $("#add-rate-form").toggle();
            });

            $("#import-excel-button").click(function() {
                $("#file-input").click();
            });

            $("#file-input").change(function(e) {
                var file = e.target.files[0];
                var formData = new FormData();
                formData.append('excel_file', file);
                formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');

                $.ajax({
                    type: "POST",
                    url: "{% url 'admin_module:upload_excel_cities' %}",
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function(response) {

                    },
                    error: function(xhr, status, error) {
                        console.error("Произошла ошибка при загрузке данных из Excel:", error);
                    }
                });
            });
        });
    </script>
<body>
    <a href="{% url 'admin_module:dictionaries' %}">Back</a>
    <h1>Cities</h1>    
    <button id="add-city-button">Add</button>
    <form method="post" id="add-city-form" style="display: none;">
        {% csrf_token %}
        <input type="text" name="city_code" placeholder="City Code">
        <input type="text" name="city_name" placeholder="City Name">
        <button type="submit">Add City</button>
    </form>
    <input type="text" id="search-city" placeholder="Enter City Code">
<button id="search-button">Search</button>

<button id="import-excel-button">Import Excel Data</button>
<form method="post" style="display: none;">
    {% csrf_token %}
    <input type="file" id="file-input" hidden>
</form>
    <table>
        <thead>
            <tr>
                <th>City Code</th>
                <th>City Name</th>
                <th>Created By</th>
                <th>Created Date</th>
                <th>Modified By</th>
                <th>Modified Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for city in cities_data %}
                <tr data-city-id="{{ city.id }}">
                    <td><span class="city-code">{{ city.city_code }}</span></td>
                    <td><span class="city-name">{{ city.city_name }}</span></td>
                    <td>{{ city.created_by }}</td>
                    <td>{{ city.created_date }}</td>
                    <td>{{ city.modified_by }}</td>
                    <td>{{ city.modified_date }}</td>
                    <td>
                        <form action="{% url 'admin_module:edit_city' city.id %}">
                            {% csrf_token %}
                            <button type="submit" class="edit-city">Edit</button>
                        </form>
                        <form action="{% url 'admin_module:delete_city' city.id %}">
                            {% csrf_token %}
                            <button type="submit" class="delete-city">Delete</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

admin_module/templates/dictionaries/commission.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Commission</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
    <script>
        $(document).ready(function() {
            console.log("Document ready.");
    
            // Function to perform the search
            function performSearch() {
                var searchQuery = $("#search-gpa").val().trim().toLowerCase();
    
                // Loop through each row and hide/show based on the search query
                $(".gpa-cell").each(function() {
                    var gpa = $(this).text().trim().toLowerCase();
                    var row = $(this).closest("tr");
    
                    if (gpa.includes(searchQuery)) {
                        row.show();
                    } else {
                        row.hide();
                    }
                });
            }
    
            $("#search-button").click(function() {
                performSearch();
            });
    
            $("#search-gpa").on("input", function() {
                performSearch();
            });

            $("#toggle-form").click(function() {
                console.log("Toggle form clicked.");
                $("#add-form").toggle();
            });
        });
    </script>
<body>
    <a href="{% url 'admin_module:dictionaries' %}">Back</a>
    <h1>Commission</h1>
    <div class="add-commission-form">
        <div class="search-box">
            <input type="text" name="search-gpa" id="search-gpa" placeholder="Search GPA" class="search-input">
            <button type="button" id="search-button">Search</button>
        </div>
        <button id="toggle-form">Add</button>
        <form method="post" id="add-form" style="display: none;">
            {% csrf_token %}
            <select name="gpa">
                {% for gpa_code in gpa_code %}
                    <option value="{{ gpa_code.id }}">{{ gpa_code.gpa_code }}</option>
                {% endfor %}
            </select>
            <input type="text" name="value" placeholder="Value" class="value-input">
            <button type="submit" class="submit-button">Add Commission</button>
        </form>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>GPA ID</th>
                <th>Commission value</th>
                <th>Created By</th>
                <th>Created Date</th>
                <th>Modified By</th>
                <th>Modified Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for commission in commission_data %}
            <tr>
                    <td class="gpa-cell">{{ commission.gpa }}</td>
                    <td class="value-cell">{{ commission.value|floatformat:0 }}</td>
                    <td>{{ commission.created_by }}</td>
                    <td>{{ commission.created_date }}</td>
                    <td>{{ commission.modified_by }}</td>
                    <td>{{ commission.modified_date }}</td>
                    <td>
                        <form action="{% url 'admin_module:edit_commission' commission.id %}">
                            {% csrf_token %}
                            <button type="submit" class="edit-commission-button">Edit</button>
                        </form>
                    
                        <form action="{% url 'admin_module:delete_commission' commission.id %}">
                            {% csrf_token %}
                            <button type="submit" class="delete-commission-button">Delete</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

admin_module/templates/dictionaries/delete_city.html
<!DOCTYPE html>
<html>
<head>
    <title>Removing the City</title>
</head>
<body>
    <h1>Removing the City</h1>
    <p>Are you sure you want to delete the city? "{{ city.city_name }}"?</p>
    <form method="post" action="{% url 'admin_module:delete_city' city.id %}">
        {% csrf_token %}
        <button type="submit">Confirm deletion</button>
        <a href="{% url 'admin_module:cities' %}">Cancel</a>
    </form>
</body>
</html>

admin_module/templates/dictionaries/delete_commission.html
<!DOCTYPE html>
<html>
<head>
    <title>Removing the City</title>
</head>
<body>
    <h1>Removing the Commission</h1>
    <p>Are you sure you want to delete the commission? "{{ commission.gpa }}"?</p>
    <form method="post" action="{% url 'admin_module:delete_commission' commission.id %}">
        {% csrf_token %}
        <input type="submit" value="Confirm deletion">
        <a href="{% url 'admin_module:commission' %}">Cancel</a>
    </form>
</body>
</html>

admin_module/templates/dictionaries/delete_kzd_rate.html
<h1>Removing the KZD Rate</h1>

<p>Are you sure you want to delete the kzd_rate? "{{ kzd_rate.rate_po|floatformat:0 }}"?</p>

<form method="post">
    {% csrf_token %}
    <button type="submit">Confim deletion</button>
    <a href="{% url 'admin_module:kzd_rates' %}">Cancel</a>
</form>

admin_module/templates/dictionaries/delete_oi_rates.html
<h1>Removing the OI Rate</h1>

<p>Are you sure you want to delete the kzd_rate? "{{ oi_rates.rate|floatformat:0 }}"?</p>

<form method="post">
    {% csrf_token %}
    <button type="submit">Confim deletion</button>
    <a href="{% url 'admin_module:oi_rates' %}">Cancel</a>
</form>

admin_module/templates/dictionaries/edit_commission.html
<!DOCTYPE html>
<html>
<head>
    <title>Edit Commission</title>
</head>
<body>
    <h1>Edit Commission</h1>
    <form method="post" action="{% url 'admin_module:edit_commission' commission.id %}">
        {% csrf_token %}
        {{ form.gpa.label_tag }} {{ form.gpa }}
        {{ form.value.label_tag}} {{ form.value}}
        <button type="submit">Save</button>
    </form>
</body>
</html>

admin_module/templates/dictionaries/edit_currency.html
<!DOCTYPE html>
<html>
<head>
    <title>Edit Currency</title>
</head>
<body>
    <h1>Edit Currency</h1>
    <form method="post" action="{% url 'admin_module:edit_currency' currency.id %}">
        {% csrf_token %}
        <input type="text" name="code" value="{{ currency.code }}">
        <input type="text" name="full_name" value="{{ currency.full_name }}">
        <input type="submit" value="Save">
    </form>
</body>
</html>

admin_module/templates/dictionaries/oi_rates.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>OI Rates</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <a href="{% url 'admin_module:dictionaries' %}">Back</a>
    <h1>OI Rates</h1>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            console.log("Document ready.");
            $("#add-rate-button").click(function() {
                console.log("Add button clicked.");
                $("#add-rate-form").toggle();
        });


            $("#add-rate-form").submit(function(e) {
                e.preventDefault();
                $.ajax({
                    type: "POST",
                    url: "{% url 'admin_module:oi_rates' %}", 
                    data: $("#add-rate-form").serialize(), 
                    success: function(response) {
                     
                        location.reload();  
                    }
                });
            });
        });
    </script>

    <button id="add-rate-button">Add</button>

    <form method="post" id="add-rate-form" style="display: none;">
        {% csrf_token %}
        <select name="city_1">
            {% for city in cities %}
                <option value="{{ city.id }}">{{ city.city_name }}</option>
            {% endfor %}
        </select>
        <select name="city_2">
            {% for city in cities %}
                <option value="{{ city.id }}">{{ city.city_name }}</option>
            {% endfor %}
        </select>
        <input type="text" name="gpa_id" placeholder="GPA ID">
        <input type="text" name="rate" placeholder="Rate">
        <input type="date" name="date_begin" placeholder="Date Begin">
        <input type="date" name="date_end" placeholder="Date End">
        <button type="submit">Add OI Rate</button>
    </form>

    <table>
        <thead>
            <tr>
                <th>City 1</th>
                <th>City 2</th>
                <th>GPA ID</th>
                <th>Rate</th>
                <th>Date Begin</th>
                <th>Date End</th>
                <th>Created By</th>
                <th>Created Date</th>
                <th>Modified By</th>
                <th>Modified Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for oi_rates in oi_rates_data %}
                <tr>
                    <td>{{ oi_rates.city_1.city_name }}</td>
                    <td>{{ oi_rates.city_2.city_name }}</td>
                    <td>{{ oi_rates.gpa_id }}</td>
                    <td>{{ oi_rates.rate|floatformat:0 }}</td>
                    <td>{{ oi_rates.date_begin }}</td>
                    <td>{{ oi_rates.date_end }}</td>
                    <td>{{ oi_rates.created_by }}</td>
                    <td>{{ oi_rates.created_date }}</td>
                    <td>{{ oi_rates.modified_by }}</td>
                    <td>{{ oi_rates.modified_date }}</td>
                    <td>
                        <form action="{% url 'admin_module:edit_oi_rates' oi_rates.id %}" >
                            {% csrf_token %}
                            <button type="submit" class="edit-oi-rates">Edit</button>
                        </form>
                        <form action="{% url 'admin_module:delete_oi_rates' oi_rates.id %}" >
                            {% csrf_token %}
                            <button type="submit" class="delete-oi-rates">Delete</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>