admin_module/urls.py
from django.urls import path
from . import views_city, views_currency, views_admin, views, views_gpa_code, views_subclass, views_commission, \
    views_exchange, views_kzd_rates, views_oi_rates, views_sdr_rates

app_name = 'admin_module'
urlpatterns = [
    path('', views.home, name='home'),
    path('main/', views.main, name='main'),
    path('login/', views.login_view, name='login'),
    path('dictionaries/', views.dictionaries_view, name='dictionaries'),
    
    path('records/',views.records, name="records"),
    path('reports/',views.reports, name="reports"),
    path('reports/cn51',views.report_cn51, name="report_cn51"),
    path('calculate_cost/', views.calculate_cost, name='calculate_cost'),

    path('add_user/', views_admin.add_user, name='add_user'),
    path('edit_user/<int:user_id>/', views_admin.edit_user, name='edit_user'),
    path('block_user/<int:user_id>/', views_admin.block_user, name='block_user'),
    path('user_list/', views_admin.user_list, name='user_list'),


    path('cities/', views_city.cities, name='cities'),
    path('cities/edit/<int:city_id>/', views_city.edit_city, name='edit_city'),
    path('cities/delete/<int:city_id>/', views_city.delete_city, name='delete_city'),
    path('upload_excel_cities', views_city.upload_excel_cities, name="upload_excel_cities"),
    
    path('currencies/', views_currency.currencies, name="currencies"),
    path('currencies/edit/<int:currency_id>/', views_currency.edit_currency, name='edit_currency'),
    path('currencies/delete/<int:currency_id>/', views_currency.delete_currency, name='delete_currency'),


    path('exchange_rates/', views_exchange.exchange_rates, name='exchange_rates'),
    path('delete_exchange_rate/<int:exchange_rate_id>/', views_exchange.delete_exchange_rate, name="delete_exchange_rate"),


    path('gpa_code/', views_gpa_code.gpa_code, name="gpa_code"),
    path('gpa_code/edit/<int:gpa_code_id>/', views_gpa_code.edit_gpa_code, name='edit_gpa_code'),
    path('gpa_code/delete/<int:gpa_code_id>/', views_gpa_code.delete_gpa_code, name='delete_gpa_code'),

    path('subclass/', views_subclass.subclass, name="subclass"),
    path('edit_subclass/<int:subclass_id>/', views_subclass.edit_subclass, name="edit_subclass"),
    path('delete_subclass/<int:subclass_id>/', views_subclass.delete_subclass, name="delete_subclass"),

    path('commission', views_commission.commission, name='commission'),
    path('commission/edit/<int:commission_id>/', views_commission.edit_commission, name='edit_commission'),
    path('commission/delete/<int:commission_id>/', views_commission.delete_commission, name='delete_commission'),

    path('kzd_rates', views_kzd_rates.kzd_rates, name="kzd_rates"),
    path('edit_kzd_rate/<int:kzd_rate_id>/', views_kzd_rates.edit_kzd_rate, name="edit_kzd_rate"),
    path('delete_kzd_rate/<int:kzd_rate_id>/', views_kzd_rates.delete_kzd_rate, name="delete_kzd_rate"),
    path('upload_excel', views_kzd_rates.upload_excel, name="upload_excel"),
    
    path('oi_rates', views_oi_rates.oi_rates, name="oi_rates"),
    path('oi_rates/edit/<int:oi_rates_id>/', views_oi_rates.edit_oi_rates, name='edit_oi_rates'),
    path('oi_rates/delete/<int:oi_rates_id>/', views_oi_rates.delete_oi_rates, name='delete_oi_rates'),

    path('sdr_rates/', views_sdr_rates.sdr_rates, name='sdr_rates'),
    path('sdr_rates/edit/<int:sdr_rates_id>/', views_sdr_rates.edit_sdr_rates, name='edit_sdr_rates'),
    path('sdr_rates/delete/<int:sdr_rates_id>/', views_sdr_rates.delete_sdr_rates, name='delete_sdr_rates'),
    path('upload_excel_sdr', views_sdr_rates.upload_excel_sdr, name="upload_excel_sdr"),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),  # Ссылка на административную панель Django
    path('', include('admin_module.urls')),  # Ссылка на ваш административный модуль

]

admin_module/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from .models import UserProfile, City, Currency, ExchangeRate, GPACode, Subclass, Commission, KZDRate, OIRate, SdrRate


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'}))


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('roles', 'status')


class CurrencyForm(forms.ModelForm):
    class Meta:
        model = Currency
        fields = '__all__'


class AddExchangeRateForm(forms.ModelForm):
    value = forms.DecimalField(max_digits=10, decimal_places=5, label='Значение')
    rate_1 = forms.ModelChoiceField(queryset=Currency.objects.all(), label='Валюта 1')
    rate_2 = forms.ModelChoiceField(queryset=Currency.objects.all(), label='Валюта 2')

    class Meta:
        model = ExchangeRate
        fields = ('value', 'rate_1', 'rate_2', 'value')


class UploadExcelForm(forms.Form):
    excel_file = forms.FileField()


class GPACodeForm(forms.ModelForm):
    class Meta:
        model = GPACode
        fields = ['gpa_code', 'description', 'gpa_full_name', 'oracle_code', 'currency']


class SubclassForm(forms.ModelForm):
    class Meta:
        model = Subclass
        fields = ['name_code', 'name_description']



class CommissionForm(forms.ModelForm):
    gpa = forms.ModelChoiceField(queryset=GPACode.objects.all())  
    class Meta:
        model = Commission
        fields = ['gpa', 'value']


class KZDRateForm(forms.ModelForm):
    city_1 = forms.ModelChoiceField(queryset=City.objects.all())
    city_2 = forms.ModelChoiceField(queryset=City.objects.all())

    class Meta:
        model = KZDRate
        fields = '__all__'
        widgets = {
            'date_begin': forms.DateInput(attrs={'type': 'date'}),
            'date_end': forms.DateInput(attrs={'type': 'date'}),
        }


class OIRateForm(forms.ModelForm):
    city_1 = forms.ModelChoiceField(queryset=City.objects.all(), empty_label="Select City 1"),
    city_2 = forms.ModelChoiceField(queryset=City.objects.all(), empty_label="Select City 2")
    class Meta:
        model = OIRate
        fields = ['city_1', 'city_2', 'gpa_id', 'rate','date_begin', 'date_end']
        widgets = {
            'date_begin': forms.DateInput(attrs={'type': 'date'}),
            'date_end': forms.DateInput(attrs={'type': 'date'}),
        }



class SdrRateForm(forms.ModelForm):
    city_1 = forms.ModelChoiceField(queryset=City.objects.all(), empty_label="Select City 1"),
    city_2 = forms.ModelChoiceField(queryset=City.objects.all(), empty_label="Select City 2")

    class Meta:
        model = SdrRate
        fields = '__all__'
        widgets = {
            'date_begin': forms.DateInput(attrs={'type': 'date'}),
            'date_end': forms.DateInput(attrs={'type': 'date'}), }


class ExcelUploadForm(forms.Form):
    excel_file = forms.FileField(label='Select an Excel file')



class ExcelImportForm(forms.Form):
    excel_file = forms.FileField()
    def clean_excel_file(self):
        excel_file = self.cleaned_data.get('excel_file')
        if excel_file:
            # Проверяем, является ли файл допустимым типом (например, .xls или .xlsx)
            allowed_extensions = ['.xls', '.xlsx']
            if not any(extension in excel_file.name for extension in allowed_extensions):
                raise forms.ValidationError('Пожалуйста, загрузите файл с расширением .xls или .xlsx.')

        return excel_file

admin_module/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from .forms import LoginForm,ExcelImportForm
import pandas as pd
from django.utils import timezone
from .models import *
from datetime import datetime
from reportlab.pdfgen import canvas
from django.db.models import Sum
from django.http import HttpResponse
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle,Spacer,Paragraph
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle


def records(request):
    if request.method == 'POST':
        form = ExcelImportForm(request.POST, request.FILES)
        if form.is_valid():
            excel_file = request.FILES['excel_file']
            df = pd.read_excel(excel_file)

            # Process DataFrame and save to the database
            for index, row in df.iterrows():
                Records.objects.create(
                    GPACode=row['GPACode'],
                    Origin=row['Origin'],
                    Destination=row['Destination'],
                    Subclass=row['Subclass'],
                    Flight1=row['Flight1'],
                    FltDate=row['FltDate'],
                    Wgt=row['Wgt'],
                    Depeche=row['Depeche'],
                    GroupDate=row['Group Date'],
                    created_by=request.user.username,
                    modified_by=request.user.username,
                    created_date = timezone.now(),
                    modified_date = timezone.now()
                )

            # Redirect to the records page
            return redirect('admin_module:records')

    else:
        form = ExcelImportForm()

    # Retrieve all records from the Report model
    records = Records.objects.all()

    # Pass the records and form to the template
    return render(request, 'admin_module/records.html', {'records': records, 'form': form})

def calculate_cost(request):
    # Получаем все записи, где Origin = 'ALA' и Destination = 'FRU'
    records = Records.objects.filter(Origin='ALA', Destination='FRU')

    # Получаем тариф для ALA -> FRU
    tariff = SdrRate.objects.filter(city_1__city_code='ALA', city_2__city_code='FRU').first()

    if tariff is not None:
        # Рассчитываем общую стоимость
        total_cost = records.aggregate(Sum('Wgt'))['Wgt__sum'] * tariff.rate
    else:
        total_cost = None

    # Получаем данные из записи Records
    records_data = Records.objects.filter(Origin='ALA', Destination='FRU').first()

    # Получаем данные из записи SdrRate
    sdr_rate_data = SdrRate.objects.filter(city_1__city_code='ALA', city_2__city_code='FRU').first()

    # Создаем PDF-документ с результатами
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="cost_calculation.pdf"'

    # Устанавливаем размер страницы
    pdf = SimpleDocTemplate(response, pagesize=letter)

    # Определяем столбцы и строки для таблицы
    columns = ["Parcours pats de destination ou groupes",
               "Categones d'envos",
               "Poids transpote au cors du ou des mois",
               "Poids total",
               "Prix du transport par kg",
               "Total des frais de transport a paye"]

    data = [
        ["1", "2", "3", "4", "5", "6"],
        ["", "Prioritaire", "kg", "kg", "SDR", "SDR"],
        ["ALA_FRU", "CP",
         str(records_data.Wgt) if records_data else "N/A",
         str(records_data.Wgt) if records_data else "N/A",
         str(sdr_rate_data.rate) if sdr_rate_data else "N/A",
         f"{total_cost:.2f}" if total_cost is not None else "N/A"],
        ["Total general", "", ""]
    ]

    # Формируем таблицу
    table_data = [columns] + data
    table = Table(table_data, colWidths=[100] * len(columns))

    # Настраиваем стиль таблицы
    style = TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)])

    table.setStyle(style)

    # Получаем стиль 'Heading2'
    heading2_style = getSampleStyleSheet()['Heading2']

    # Собираем документ
    elements = [
    table, Spacer(1, 12), Spacer(1, 12),
    Spacer(1, 6),
    Paragraph(
        "<u>Administration creancire</u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<u>Vue et accepte par l'Administration debitrice</u>",
        style=ParagraphStyle(
            'Heading2',
            fontSize=10,
            spaceBefore=100,
            spaceAfter=6,
        )
    ),

    Paragraph(
            "<u>Signature</u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<u>Lieu,date et signature</u>",

              style=ParagraphStyle(
                  'Heading2',
                  fontSize=10,
                  spaceBefore=6,
                  spaceAfter=6,
              )
              )
]

    pdf.build(elements)


    return response


def home(request):
    return render(request, 'admin_module/admin_home.html')


def main(request):
    return render(request, 'admin_module/main.html')   

def reports(request):
    return render(request, 'admin_module/reports.html')   

def report_cn51(request):
    return render(request, 'admin_module/report_cn51.html')   


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('admin_module:main')
    else:
        form = LoginForm()

    return render(request, 'admin_module/login.html', {'form': form})


def dictionaries_view(request):
    return render(request, 'admin_module/dictionaries.html')

admin_module/templates/admin_module/add_user.html
{% extends 'admin/base.html' %}

{% block content %}
  <h2>Добавление пользователя</h2>
  <form method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">Создать пользователя</button>
  </form>
  <a href="{% url 'admin_module:user_list' %}">Назад к списку пользователей</a>
{% endblock %}

admin_module/templates/admin_module/admin_home.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Welcome</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <h1>Welcome to Main page</h1>

    <button id="login-button">Login</button>
    

    <script>
        $(document).ready(function() {
            // Redirect to the authentication page when the "Login" button is clicked
            $("#login-button").click(function() {
                window.location.href = "/login/";
            });
        });
    </script>
</body>
</html>

admin_module/templates/admin_module/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <title>Hello, world!</title>
  </head>
  <body>
  
{% include 'admin_module/navbar.html' %}
    <!-- Здесь навигация иимя пользователя или ссылка на вход -->
{% block content %}
{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

admin_module/templates/admin_module/dictionaries.html
<a href="{% url 'admin_module:main' %}">Back</a>
<h1>Dictionaries</h1>

<ul>
    <li><a href="{% url 'admin_module:cities' %}">Cities</a></li>
    <li><a href="{% url 'admin_module:currencies' %}">Currency</a></li>
    <li><a href="{% url 'admin_module:exchange_rates' %}">Exchange Rates</a></li>
    <li><a href="{% url 'admin_module:gpa_code' %}">GPA Code</a></li>
    <li><a href="{% url 'admin_module:subclass' %}">Subclass</a></li>
    <li><a href="{% url 'admin_module:sdr_rates' %}">SDR Rates</a></li>
    <li><a href="{% url 'admin_module:kzd_rates' %}">KZD Rates</a></li>
    <li><a href="{% url 'admin_module:commission' %}">Commission</a></li>
    <li><a href="{% url 'admin_module:oi_rates' %}">OI Rates</a></li>

</ul>
<style>
h1 {
    text-align: center;
    font-size: 24px; 
    margin: 20px 0;   
}

ul {
    list-style: none; 
    padding: 0;       
}

li {
    margin-bottom: 10px;  
}

a {
    text-decoration: none;  
    color: #007BFF;      
}

a:hover {
    color: #0056b3;  
}
</style>

admin_module/templates/admin_module/edit_user.html
<!DOCTYPE html>
<html>
<head>
    <title>Редактировать пользователя</title>
</head>
<body>
    <h1>Редактировать пользователя: {{ user.username }}</h1>

    <form method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <button type="submit">Сохранить</button>
    </form>

    <a href="{% url 'admin_module:user_list' %}">Назад к списку пользователей</a>
</body>
</html>

admin_module/templates/admin_module/login.html
{% block content %}
    <h2>Авторизация</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.username.label_tag }} {{ form.username }}
        <br>
        {{ form.password.label_tag }} {{ form.password }}
        <br>
        <button type="submit">Войти</button>
    </form>
{% endblock %}

admin_module/templates/admin_module/main.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main</title>
</head>
<body>
    <ul>
        <li><a href="{% url 'admin_module:dictionaries' %}">Dictionaries</a></li>
        <li><a href="{% url 'admin_module:records' %}">Records</a></li>
        <li><a href="{% url 'admin_module:reports' %}">Reports</a></li>
        <li><a href="{% url 'admin_module:dictionaries' %}">Documentation</a></li>
    </ul>
</body>
</html>
<style>

    
    ul {
        list-style: none; 
        padding: 5px;      
        display: flex;
        justify-content: center;
    }
    li{
        margin: 20px;
    }
    
    a {
        text-decoration: none; 
    }
    </style>

admin_module/templates/admin_module/records.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Records</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <h1>Records</h1>
    

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Загрузить</button>
    </form>

    <table>
        <thead>
            <tr>
                <th>GPACode</th>
                <th>Origin</th>
                <th>Destination</th>
                <th>Subclass</th>
                <th>Flight1</th>
                <th>FltDate</th>
                <th>Wgt</th>
                <th>Depeche</th>
                <th>Group Date</th>
                <th>Created By</th>
                <th>Created Date</th>
                <th>Modified By</th>
                <th>Modified Date</th>
            </tr>
        </thead>
        <tbody>
            {% for record in records %}
                <tr>
                    <td>{{ record.GPACode }}</td>
                    <td>{{ record.Origin }}</td>
                    <td>{{ record.Destination }}</td>
                    <td>{{ record.Subclass }}</td>
                    <td>{{ record.Flight1 }}</td>
                    <td>{{ record.FltDate }}</td>
                    <td>{{ record.Wgt }}</td>
                    <td>{{ record.Depeche }}</td>
                    <td>{{ record.GroupDate }}</td>
                    <td>{{ record.created_by }}</td>
                    <td>{{ record.created_date }}</td>
                    <td>{{ record.modified_by }}</td>
                    <td>{{ record.modified_date }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

admin_module/templates/admin_module/report_cn51.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Report CN51</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </head>
<body>
  
  <style>
    table {
      border-collapse: collapse;
      width: 100%;
    }

    table, th, td {
      border: 1px solid black;
    }

    th, td {
      padding: 10px;
      text-align: left;
    }

    th {
      background-color: #f2f2f2;
    }
  </style>
</head>
<body>

  <table>
    <thead>
      <tr>
        <th>Parcours pats de destination ou groupes</th>
        <th>Categones d'envos</th>
        <th>Poidstranspote au cors du o u des mois</th>
        <th>Poids total</th>
        <th>Prix du transport par kg</th>
        <th>Total des frais de transpont a paye</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1</td>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>5</td>
        <td>6</td>
      </tr>
      <tr>
        <td></td>
        <td>Prioritaire</td>
        <td>kg</td>
        <td>kg</td>
        <td>SDR</td>
        <td>SDR</td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
      <td>Total general</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>

      
    </tbody>
  </table>
<form action="{% url 'admin_module:calculate_cost' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Рассчитать стоимость">
    </form>

    <style>
    h1 {
        text-align: center;
        font-size: 24px; 
        margin: 20px 0;   
    }
    
    ul {
        list-style: none; 
        padding: 0;       
    }
    
    li {
        margin-bottom: 10px;  
    }
    
    a {
        text-decoration: none;  
        color: #007BFF;      
    }
    
    a:hover {
        color: #0056b3;  
    }
</style>
</head>






</body>

</html>

admin_module/templates/admin_module/report_cn51_calc.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Report CN51</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </head>
<body>
    <form action="{% url 'admin_module:calculate_cost' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Рассчитать стоимость">
    </form>
    <style>
    h1 {
        text-align: center;
        font-size: 24px; 
        margin: 20px 0;   
    }
    
    ul {
        list-style: none; 
        padding: 0;       
    }
    
    li {
        margin-bottom: 10px;  
    }
    
    a {
        text-decoration: none;  
        color: #007BFF;      
    }
    
    a:hover {
        color: #0056b3;  
    }
    </style>
</body>

</html>

admin_module/templates/admin_module/reports.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Reports</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </head>
<body>
    <ul>
        <li><a href="{% url 'admin_module:report_cn51' %}">CN51</a></li>

    
    </ul>
    <style>
    h1 {
        text-align: center;
        font-size: 24px; 
        margin: 20px 0;   
    }
    
    ul {
        list-style: none; 
        padding: 0;       
    }
    
    li {
        margin-bottom: 10px;  
    }
    
    a {
        text-decoration: none;  
        color: #007BFF;      
    }
    
    a:hover {
        color: #0056b3;  
    }
    </style>
</body>

</html>

admin_module/templates/admin_module/user_list.html
{% extends 'admin/base.html' %}

{% block content %}
  <h2>Список пользователей</h2>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Login</th>
        <th>Name</th>
        <th>Roles</th>
        <th>Status</th>
        <!-- Другие поля, которые вы хотите отобразить -->
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
        <tr>
          <td>{{ user.id }}</td>
          <td>{{ user.user.username }}</td>
          <td>{{ user.user.first_name }} {{ user.user.last_name }}</td>
          <td>{{ user.roles }}</td>
          <td>{{ user.status }}</td>
           <td>
                    <a href="{% url 'admin_module:edit_user' user.user.id %}">Редактировать</a>
                </td>
          <!-- Отображение других полей модели UserProfile -->
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'admin_module:add_user' %}">Добавить пользователя</a> <br>
{% endblock %}